name: "PHVC"

on:
  schedule:
    - cron: "0 0,12 * * *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./CheckMissVideo.py
          
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: .  # Вказано ".", щоб артефакти завантажилися в корінь проекту

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts

      - name: Restore Artifacts
        run: |
          # Тут ви можете скопіювати або пересунути файли з завантажених артефактів
          cp -r my-artifacts/* .
