name: "PHVC"

on:
  schedule:
    - cron: "0 0,8,16 * * *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./CheckMissVideo.py
          
      - name: Commit and Push Changes
        run: |
            # Configure Git with your user information
            git config --global user.email "oliynik.v2014@gmail.com"
            git config --global user.name "slavikfoxy"
        
            # Add all changes to the staging area
            git add .
        
            # Commit changes with a custom message
            git commit -m "Commit message from GitHub Actions"
        
            # Push changes to the repository
            git push origin main
